ARG PYCLOWDER_PYTHON="3"
FROM maxzilla2/extractors-simple-extractor:se

ENV EXTRACTION_FUNC="flir2tif"
ENV EXTRACTION_MODULE="transformer"

# Install applications we need
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3-gdal \
        gdal-bin

# Install Python updates
RUN python3 -m pip install --upgrade --no-cache-dir pip
RUN python3 -m pip install --upgrade --no-cache-dir setuptools
RUN python3 -m pip install --upgrade --no-cache-dir numpy

COPY extractor_info.json /home/extractor